Repository kartik3805/QuickWiKi, pull requests merged in 2022-10, with the labels that each got.

#16 Complete page responsiveness
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#19 Improved Search input can enter to submit.
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 added favicon
  images/favicon.ico
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#31 Centered search input
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 Fix : No margin in 'steps paragraph', in mobile devices [fixes #35]
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 previous content disappears when error message is displayed
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#40 added footer
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#42 Update script.js
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#48 Create LICENSE.md
  LICENSE.md
Labels: hacktoberfest, hacktoberfest-accepted

#51 fixed error message issue
  script.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#54 updated github icon color
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#56 Readme Wikipedia url fixed
  readme.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#62 refactor: wrap up search section inside form tag
  index.html
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#64 Fixed Mobile Glitch
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#65 Add hover background to the submit button
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 Modified texts, alerts to acknowledge user about topic search
  index.html
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
